project_name: ado-jobs-queue

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - binary: ado-jobs-queue
    id: ado-jobs-queue-linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -w -s -X 'github.com/cdalar/ado-jobs-queue/cmd.Version=v{{.Version}}-{{.ShortCommit}}'

  - binary: ado-jobs-queue
    id: ado-jobs-queue
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64 # M1 Chip
    ldflags:
      - -w -s -X 'github.com/cdalar/ado-jobs-queue/cmd.Version=v{{.Version}}-{{.ShortCommit}}'
    # hooks:
    #   post: ["gon gon/config-{{.Arch}}.json"]


archives:
  - id: repl
    name_template: "{{ .ProjectName }}-{{.Os}}-{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # files:
    #   - non-existent*

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: cdalar
    name: ado-jobs-queue
  prerelease: auto

brews:
  - repository:
      owner: cdalar
      name: homebrew-tap
    description: "ado-jobs-queue"
