name: vuln

permissions: 
  contents: read
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  run:
    name: Vuln
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...
